services:
  signald:
    image: signald/signald
    volumes:
      - signald:/signald
  tcp-relay:
    image: alpine/socat
    depends_on:
      - signald
    ports:
      - 12345:12345
    command: tcp-listen:12345,fork,reuseaddr unix-connect:/signald/signald.sock
    volumes:
      - signald:/signald

volumes:
  signald:
